### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by shouxd** [paulevsGitch/BetterEnd#41]
https://pastebin.com/ftncQRsA

**Comment by paulevsGitch** [comment]
Looks like something interrupt structure loading and structure was loaded before blocks were initiated, I will try to fix this

**Comment by paulevsGitch** [comment]
Now all structures will be loaded during world generation, this will fix issue. Fix will be available in the next patch

**Comment by paulevsGitch** [comment]
Fixed in 0.8.5

**Comment by shouxd** [comment]
hi, Im afraid Im still getting a crash on startup. This is with latest betterend release: https://pastebin.com/tCiMm0Pa

**Comment by paulevsGitch** [comment]
This is probably a hydrogen mod issue, you can try to run your modpack without it

**Comment by shouxd** [comment]
I tried removing Hydrogen and it worked:) However Im curious if there's maybe a way to make it compatible?

**Comment by paulevsGitch** [comment]
This is a known Hydrogen issue, it somehow breaks how blocks are initializing. It will probably be fixed from Hydrogen side someday (at least jellysquid3 knows about this problem)
